name: Run ETL to BigQuery

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # manual run

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write GCP credentials to file
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > gcp_key.json

      - name: Export environment variables
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=gcp_key.json" >> $GITHUB_ENV
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY_GH }}" >> $GITHUB_ENV

      - name: Run ETL
        run: python main.py